# Generated by Django 5.2.16 on 2026-09-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_leadattribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='anchor_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço âncora travado'),
        ),
        migrations.AddField(
            model_name='lead',
            name='card_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor da parcela cartão'),
        ),
        migrations.AddField(
            model_name='lead',
            name='card_installments',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='parcelas cartão'),
        ),
        migrations.AddField(
            model_name='lead',
            name='card_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço cartão travado'),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='desconto promocional aplicado'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pix_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço PIX travado'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='snapshot completo dos valores na captura'),
        ),
        migrations.AddField(
            model_name='lead',
            name='promoter_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='nome do promotor na captura'),
        ),
    ]
