# Generated by Django 5.2.16 on 2026-09-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas', '0005_add_static_pix_qr_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
